# Generacion de datos sinteticos

In [1]:
import pandas as pd
import numpy as np
import random
import json
from faker import Faker
from datetime import datetime, timedelta

In [2]:
fake = Faker("es_ES")
random.seed(42)
np.random.seed(42)

N_CLIENTES = 300
N_PRODUCTOS = 200
N_TIENDAS = 20
N_EMPLEADOS = 20
N_VENTAS = 2000

In [3]:
PROVINCIAS_CIUDADES = {
    "Pichincha": ["Quito", "Cayambe", "Rumiñahui"],
    "Guayas": ["Guayaquil", "Durán", "Samborondón"],
    "Azuay": ["Cuenca", "Gualaceo"],
    "Manabí": ["Manta", "Portoviejo"],
    "Tungurahua": ["Ambato", "Baños"],
    "El Oro": ["Machala", "Santa Rosa"]
}

SEGMENTOS = ["Frecuente", "Nuevo", "Corporativo", "Premium"]
GENEROS = ["Masculino", "Femenino", "No especificado"]

CATEGORIAS = {
    "Electrónica": ["Audio", "Computación", "Telefonía"],
    "Hogar": ["Cocina", "Decoración", "Muebles"],
    "Deportes": ["Fitness", "Outdoor", "Accesorios"],
    "Moda": ["Ropa", "Calzado", "Accesorios"],
    "Oficina": ["Papelería", "Mobiliario", "Tecnología"]
}

MARCAS = [
    "Samsung", "LG", "Sony", "Xiaomi", "HP", "Lenovo",
    "Ikea", "Nike", "Adidas", "Mabe", "Whirlpool", "Genérica"
]

ESTADOS_PRODUCTO = ["activo", "inactivo", "descontinuado"]
TIPOS_TIENDA = ["Fisica", "Outlet", "Express", "Mall"]
SERVICIOS = ["Entrega a domicilio", "Retiro en tienda", "Soporte técnico", "Parqueadero", "Pago QR"]
METODOS_PAGO = ["Tarjeta", "Efectivo", "Transferencia", "PayPal"]
CANALES_VENTA = ["Online", "Presencial", "App"]
ESTADOS_VENTA = ["completada", "completada", "completada", "anulada"]  # sesgo intencional

CARGOS = ["Vendedor", "Supervisor", "Cajero", "Asesor comercial"]

In [4]:
empleados = []
for i in range(1, N_EMPLEADOS + 1):
    provincia = random.choice(list(PROVINCIAS_CIUDADES.keys()))
    ciudad = random.choice(PROVINCIAS_CIUDADES[provincia])

    empleados.append({
        "id_empleado": i,
        "nombre_empleado": fake.name(),
        "cargo": random.choice(CARGOS),
        "canal_base": random.choice(CANALES_VENTA),
        "ciudad_base": ciudad,
        "provincia_base": provincia
    })

df_empleados = pd.DataFrame(empleados)
df_empleados.head()

,id_empleado,nombre_empleado,cargo,canal_base,ciudad_base,provincia_base
0,1,Sabas Manrique Rosselló,Vendedor,App,Machala,El Oro
1,2,Paulino Onofre Calderón Piñeiro,Supervisor,Online,Cuenca,Azuay
2,3,Lupe Rosado Gálvez,Vendedor,App,Machala,El Oro
3,4,Horacio Puga Peñalver,Vendedor,Online,Manta,Manabí
4,5,Zaira de Oliveras,Vendedor,App,Guayaquil,Guayas

In [5]:
clientes = []
for i in range(1, N_CLIENTES + 1):
    provincia = random.choice(list(PROVINCIAS_CIUDADES.keys()))
    ciudad = random.choice(PROVINCIAS_CIUDADES[provincia])

    clientes.append({
        "id_cliente": i,
        "nombre": fake.first_name(),
        "apellido": fake.last_name(),
        "email": fake.unique.email(),
        "telefono": fake.phone_number(),
        "ciudad": ciudad,
        "provincia": provincia,
        "segmento": random.choice(SEGMENTOS),
        "fecha_registro": fake.date_between(start_date="-3y", end_date="today"),
        "edad": random.randint(18, 75),
        "genero": random.choice(GENEROS)
    })

df_clientes = pd.DataFrame(clientes)
df_clientes.head()

,id_cliente,nombre,apellido,email,telefono,ciudad,provincia,segmento,fecha_registro,edad,genero
0,1,Valeria,Gonzalez,maria-del-carmen81@example.com,+34955 054 927,Portoviejo,Manabí,Nuevo,2023-04-09,61,Femenino
1,2,Lucho,Royo,abellancustodio@example.net,+34 847 19 61 45,Quito,Pichincha,Frecuente,2024-08-27,69,Femenino
2,3,Florencio,Montenegro,vheras@example.net,+34820 60 93 36,Portoviejo,Manabí,Frecuente,2026-01-14,31,No especificado
3,4,David,Montenegro,ifranco@example.org,+34980 65 78 83,Santa Rosa,El Oro,Nuevo,2024-07-01,59,Femenino
4,5,Gregorio,Avilés,cabreroamerica@example.com,+34983029796,Portoviejo,Manabí,Nuevo,2025-12-14,34,Masculino

In [6]:
productos = []
for i in range(1, N_PRODUCTOS + 1):
    categoria = random.choice(list(CATEGORIAS.keys()))
    subcategoria = random.choice(CATEGORIAS[categoria])
    marca = random.choice(MARCAS)

    precio_lista = round(random.uniform(8, 1500), 2)
    costo_unitario = round(precio_lista * random.uniform(0.45, 0.80), 2)

    productos.append({
        "id_producto": i,
        "sku": fake.unique.bothify(text="SKU-#####"),
        "nombre_producto": f"{fake.word().capitalize()} {fake.word().capitalize()}",
        "categoria": categoria,
        "subcategoria": subcategoria,
        "marca": marca,
        "precio_lista": precio_lista,
        "costo_unitario": costo_unitario,
        "stock": random.randint(0, 300),
        "estado_producto": random.choice(ESTADOS_PRODUCTO),
        "fecha_creacion": fake.date_between(start_date="-2y", end_date="today")
    })

df_productos = pd.DataFrame(productos)
df_productos.head()

,id_producto,sku,nombre_producto,categoria,subcategoria,marca,precio_lista,costo_unitario,stock,estado_producto,fecha_creacion
0,1,SKU-16416,Carlos Pudo,Electrónica,Computación,Sony,1203.57,801.99,185,activo,2024-05-26
1,2,SKU-33985,Dicen Siendo,Moda,Ropa,Xiaomi,658.03,388.34,40,inactivo,2024-07-22
2,3,SKU-68720,Lejos Debido,Deportes,Accesorios,Lenovo,338.59,244.70,39,descontinuado,2026-01-24
3,4,SKU-27631,Resulta Casa,Electrónica,Telefonía,Adidas,297.30,214.56,179,descontinuado,2024-06-09
4,5,SKU-52043,Puerta Cantidad,Hogar,Cocina,LG,226.49,117.56,78,descontinuado,2025-05-15

In [7]:
tiendas = []

for i in range(1, N_TIENDAS + 1):
    provincia = random.choice(list(PROVINCIAS_CIUDADES.keys()))
    ciudad = random.choice(PROVINCIAS_CIUDADES[provincia])

    if provincia in ["Guayas", "Manabí", "El Oro"]:
        region = "Costa"
    else:
        region = "Sierra"

    tienda = {
        "id_tienda": i,
        "nombre_tienda": f"Tienda {fake.company()}",
        "ciudad": ciudad,
        "provincia": provincia,
        "region": region,
        "tipo_tienda": random.choice(TIPOS_TIENDA),
        "horarios": {
            "lunes_viernes": "09:00-18:00",
            "sabado": "10:00-16:00",
            "domingo": random.choice(["cerrado", "10:00-14:00"])
        },
        "contacto": {
            "telefono": fake.phone_number(),
            "email": fake.company_email()
        },
        "servicios": random.sample(SERVICIOS, k=random.randint(2, 5)),
        "rating": round(random.uniform(3.2, 5.0), 1),
        "geo": {
            "lat": round(random.uniform(-4.5, 0.5), 6),
            "lon": round(random.uniform(-81.0, -75.0), 6)
        }
    }
    tiendas.append(tienda)

len(tiendas), tiendas[0]

(20,
 {'id_tienda': 1,
  'nombre_tienda': 'Tienda Desarrollo Gabaldón S.Coop.',
  'ciudad': 'Manta',
  'provincia': 'Manabí',
  'region': 'Costa',
  'tipo_tienda': 'Fisica',
  'horarios': {'lunes_viernes': '09:00-18:00',
   'sabado': '10:00-16:00',
   'domingo': 'cerrado'},
  'contacto': {'telefono': '+34 824 495 728',
   'email': 'nicolascanales@infraestructuras.com'},
  'servicios': ['Retiro en tienda',
   'Pago QR',
   'Parqueadero',
   'Soporte técnico'],
  'rating': 3.9,
  'geo': {'lat': -0.638289, 'lon': -77.46846}})

In [8]:
productos_lookup = df_productos.set_index("id_producto").to_dict("index")
clientes_ids = df_clientes["id_cliente"].tolist()
productos_ids = df_productos["id_producto"].tolist()
tiendas_ids = [t["id_tienda"] for t in tiendas]
empleados_ids = df_empleados["id_empleado"].tolist()

In [9]:
ventas = []
fecha_inicio = datetime(2025, 1, 1)
fecha_fin = datetime(2026, 3, 31)
dias_rango = (fecha_fin - fecha_inicio).days

for i in range(1, N_VENTAS + 1):
    id_producto = random.choice(productos_ids)
    id_cliente = random.choice(clientes_ids)
    id_tienda = random.choice(tiendas_ids)
    id_empleado = random.choice(empleados_ids)

    producto = productos_lookup[id_producto]
    empleado = df_empleados.loc[df_empleados["id_empleado"] == id_empleado].iloc[0]

    fecha_venta = fecha_inicio + timedelta(days=random.randint(0, dias_rango))
    cantidad = random.randint(1, 8)

    precio_base = float(producto["precio_lista"])
    variacion = random.uniform(0.90, 1.05)
    precio_unitario = round(precio_base * variacion, 2)

    venta_bruta = cantidad * precio_unitario
    descuento = round(venta_bruta * random.choice([0, 0.05, 0.10, 0.15]), 2)

    ventas.append({
        "id_venta": i,
        "fecha_venta": fecha_venta.date(),
        "id_cliente": id_cliente,
        "id_producto": id_producto,
        "id_tienda": id_tienda,
        "id_empleado": id_empleado,
        "nombre_empleado": empleado["nombre_empleado"],
        "cargo": empleado["cargo"],
        "cantidad": cantidad,
        "precio_unitario": precio_unitario,
        "descuento": descuento,
        "metodo_pago": random.choice(METODOS_PAGO),
        "canal_venta": random.choice(CANALES_VENTA),
        "estado_venta": random.choice(ESTADOS_VENTA)
    })

df_ventas = pd.DataFrame(ventas)
df_ventas.head()

,id_venta,fecha_venta,id_cliente,id_producto,id_tienda,id_empleado,nombre_empleado,cargo,cantidad,precio_unitario,descuento,metodo_pago,canal_venta,estado_venta
0,1,2025-12-19,1,117,14,7,Luis Peinado Feijoo,Vendedor,3,1326.92,398.08,Efectivo,Presencial,completada
1,2,2025-07-10,185,168,9,3,Lupe Rosado Gálvez,Vendedor,3,413.54,124.06,Efectivo,Presencial,completada
2,3,2025-09-02,49,181,1,7,Luis Peinado Feijoo,Vendedor,2,153.60,15.36,PayPal,Online,completada
3,4,2025-12-22,176,179,4,14,Coral Luna Durán,Vendedor,3,132.01,19.80,PayPal,Online,completada
4,5,2025-03-12,161,27,12,10,Carolina Real Coello,Vendedor,7,1472.89,515.51,Efectivo,Online,completada

In [10]:
print("Clientes:", df_clientes.shape)
print("Productos:", df_productos.shape)
print("Empleados:", df_empleados.shape)
print("Ventas:", df_ventas.shape)
print("Tiendas:", len(tiendas))

print("\nVentas nulas por columna:")
print(df_ventas.isnull().sum())

print("\nEstados de venta:")
print(df_ventas["estado_venta"].value_counts())

print("\nProductos referenciados inexistentes en ventas:",
      ~df_ventas["id_producto"].isin(df_productos["id_producto"]).all())

print("Clientes referenciados inexistentes en ventas:",
      ~df_ventas["id_cliente"].isin(df_clientes["id_cliente"]).all())

Clientes: (300, 11)
Productos: (200, 11)
Empleados: (20, 6)
Ventas: (2000, 14)
Tiendas: 20

Ventas nulas por columna:
id_venta           0
fecha_venta        0
id_cliente         0
id_producto        0
id_tienda          0
id_empleado        0
nombre_empleado    0
cargo              0
cantidad           0
precio_unitario    0
descuento          0
metodo_pago        0
canal_venta        0
estado_venta       0
dtype: int64

Estados de venta:
estado_venta
completada    1505
anulada        495
Name: count, dtype: int64

Productos referenciados inexistentes en ventas: False
Clientes referenciados inexistentes en ventas: False

# Guardar archivos sinteticos en la carpeta "data" del proyecto

In [11]:
import os

os.makedirs("../data", exist_ok=True)

df_clientes.to_csv("../data/clientes.csv", index=False)
df_productos.to_csv("../data/productos.csv", index=False)
df_ventas.to_csv("../data/ventas.csv", index=False)

with open("../data/tiendas.json", "w", encoding="utf-8") as f:
    json.dump(tiendas, f, ensure_ascii=False, indent=2, default=str)

print("Archivos exportados en ../data")

Archivos exportados en ../data

# Levantar Docker Compose para iniciar los contenedores de PostgreSQL y MongoDB
``` bash
docker-compose up -d
```
Verificar que los contenedores estén corriendo
``` bash
docker ps
```

# Cargar datos en MySQL, PostgreSQL y MongoDB

In [12]:
%pip install sqlalchemy pymysql psycopg2-binary pymongo

Requirement already satisfied: sqlalchemy in c:\users\zevbetaultra7\anaconda3\lib\site-packages (2.0.45)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: pymongo in c:\users\zevbetaultra7\anaconda3\lib\site-packages (4.16.0)
Requirement already satisfied: greenlet>=1 in c:\users\zevbetaultra7\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\zevbetaultra7\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in c:\users\zevbetaultra7\anaconda3\lib\site-packages (from pymongo) (2.8.0)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Downloading psycopg2_binary-2.9.11-cp313-cp313-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ------------------- -------------------- 1.3/2.7 MB 5.5 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 5.4 MB/s  0:00:00
Installing collected packages: pymysql, psycopg2-binary

   -------------------- ------------------- 1/2 [psycopg2-binary]
   ---------------------------------------- 2/2 [psycopg2-binary]

Successfully installed psycopg2-binary-2.9.11 pymysql-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [13]:
from sqlalchemy import create_engine
from pymongo import MongoClient
import pandas as pd
import json

In [14]:
df_clientes = pd.read_csv("../data/clientes.csv")
df_productos = pd.read_csv("../data/productos.csv")
df_ventas = pd.read_csv("../data/ventas.csv")

with open("../data/tiendas.json", "r", encoding="utf-8") as f:
    tiendas = json.load(f)

In [15]:
mysql_engine = create_engine("mysql+pymysql://root:root@localhost:3307/origen_mysql")

df_clientes.to_sql(
    "clientes",
    con=mysql_engine,
    if_exists="replace",
    index=False
)

print("Clientes cargados en MySQL.")

Clientes cargados en MySQL.

In [16]:
pd.read_sql("SELECT COUNT(*) AS total_clientes FROM clientes", mysql_engine)

   total_clientes
0             300

In [17]:
pg_engine = create_engine("postgresql+psycopg2://postgres:postgres@localhost:5432/origen_pg")

df_productos.to_sql(
    "productos",
    con=pg_engine,
    if_exists="replace",
    index=False
)

print("Productos cargados en PostgreSQL.")

Productos cargados en PostgreSQL.

In [18]:
pd.read_sql('SELECT COUNT(*) AS total_productos FROM productos', pg_engine)

   total_productos
0              200

In [19]:
mongo_client = MongoClient("mongodb://localhost:27017/")
mongo_db = mongo_client["origen_mongo"]
mongo_collection = mongo_db["tiendas"]

mongo_collection.delete_many({})
mongo_collection.insert_many(tiendas)

print("Tiendas cargadas en MongoDB.")

Tiendas cargadas en MongoDB.

In [20]:
mongo_collection.count_documents({})

20

In [21]:
print("Clientes MySQL:", pd.read_sql("SELECT COUNT(*) AS total FROM clientes", mysql_engine)["total"][0])
print("Productos PostgreSQL:", pd.read_sql("SELECT COUNT(*) AS total FROM productos", pg_engine)["total"][0])
print("Tiendas MongoDB:", mongo_collection.count_documents({}))
print("Ventas CSV:", len(df_ventas))

Clientes MySQL: 300
Productos PostgreSQL: 200
Tiendas MongoDB: 20
Ventas CSV: 2000

# Crear dw_schema en PostgreSQL para el Data Warehouse

tenemos que ejecutar para crear el Data Warehouse en PostgreSQL. Para ello, usamos el esquema sql creado para el Data Warehouse:

```bash
Get-Content sql/dw_schema.sql | docker exec -i postgres_etl psql -U postgres -d origen_pg
```

Luego,:

```bash
docker exec -it postgres_etl psql -U postgres -d dw_retail
```

seguido de:

```bash
\dt
```

Verificar estado y conexión a la base de datos:

```bash
docker ps

**Verificar PostgreSQL**
```bash
docker exec -it postgres_etl psql -U postgres
```
**ver todas las bases de datos**
```sql
\l
```

**Acceder a la base de datos, observar tablas y salir**
```bash
docker exec -it postgres_etl psql -U postgres
```

```sql
\c dw_retail
\dt
\q 
```

**Verificar MySQL**
```bash
docker exec -it mysql_etl mysql -uroot -proot
```
**ver todas las bases de datos**
```sql
SHOW DATABASES;
```
**Acceder a la base de datos, observar tablas y salir**
```SQL
USE origen_mysql;
SHOW TABLES;
SELECT COUNT(*) FROM clientes;
exit
```

**verificar MongoDB**
```bash
docker exec -it mongo_etl mongosh
```
**ver todas las bases de datos**
```javascript
show dbs
```
**Acceder a la base de datos, observar colecciones y salir**
```javascript
use origen_mongo
show collections
db.clientes.countDocuments()
db.tiendas.findOne()
exit
```

**verificar archivo CSV**
```bash
dir data

**comprobar ventas**
```bash
python -c "import pandas as pd; print(pd.read_csv('data/ventas.csv').shape)"